### ISSUE TITLE
System Password?

### ISSUE THREAD

**Issue by ksmanu1997** [yibudak/3jcn31ww-mod#3]
I Flash this file and it works on my laptop but need system password to enter in bios. So please tell me what is the BIOS System Password?

**Comment by yibudak** [comment]
There shouldn't be a password with clean bios file. Double check if you successfully flashed the bios.

**Comment by ksmanu1997** [comment]
I completely erase my BIOS chip by ch341a programmer and flash your file but when I enter in BIOS it requires system password. Does the programmer incorrectly flash my BIOS? Pls help

**Comment by ksmanu1997** [comment]
Any other way to erase password?

**Comment by yibudak** [comment]
> Any other way to erase password?

Since I don't have this laptop anymore I can't help, but you will solve the problem by yourself with following these steps:
https://github.com/yibudak/3jcn31ww-mod/issues/2#issuecomment-1680812327

**Comment by ksmanu1997** [comment]
Ok Thank you! I will try.
